src/color.rs
src/nth.rs
src/parser.rs
src/serializer.rs
src/tests.rs
src/tokenizer.rs

r? @jdm
This also changes the numeric types in tokens from `f64` / `i64` to `f32` / `i32`, which might requires some changes in Servo.

Clamp to MAX / INFINITY rather than panic on overflow in number parsing

---

Cargo.toml
src/color.rs
src/lib.rs

`serde` is an optional Cargo feature.
r? @SimonSapin

Allow colors to be serialized with `serde`.

---

src/tokenizer.rs

It's quite slow compared to multiplication.
r? @SimonSapin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/81)

tokenizer: Remove division from the floating point conversion code.

---

Cargo.toml

r? @SimonSapin
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/82)

Bump version number for release.

---

.travis.yml
Cargo.toml
src/color.rs
src/lib.rs

Part of servo/heapsize#5.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/85)

Add HeapSizeOf support.

---

Cargo.toml
src/parser.rs
src/tokenizer.rs

This helps implementing CSS Custom Properties in Servo.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/87)

Add tracking of `var()` functions.

---

Cargo.toml
src/lib.rs
src/serializer.rs
src/tests.rs

Servo will use this for custom property values which are conceptually sequences of tokens, but are represented in memory as strings. When concatenating such strings, an empty comment `/**/` sometimes needs to be inserted so that two tokens are not reparsed as one.
r? @pcwalton
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/89)

Add "token serialization types".

---

Cargo.toml
src/parser.rs
src/serializer.rs
src/tests.rs
src/tokenizer.rs

Only unquoted URLs are special tokens now. Use `Parser::expect_url`.
This is a [breaking-change]. The version number was incremented accordingly.
This change will help with https://github.com/servo/servo/issues/7767
This triggers https://github.com/rust-lang/rust/issues/28934 and fails to build in the current Rust nightly, but works fine in the Rust version that Servo currently use. Hopefully that rustc bug will be fixed before we need to upgrade Rust in Servo.
r? @mbrubeck
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/90)

Treat url(<string>) as a normal functions, per spec change.

---

Cargo.toml
src/color.rs
src/lib.rs
src/nth.rs

Change the usage syntax to require a comma on the last non-fallback arm, which is a [breaking-change].
The old definition has started to emit a warning in recent nightlies and is likely to be an error in future versions: https://github.com/rust-lang/rfcs/pull/1384
The new definition is recursive to resolve ambiguities. Unfortunately this makes error reporting terrible: https://github.com/rust-lang/rust/issues/31022
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/91)

Make match_ignore_ascii_case! future-proof.

---

Cargo.toml

I just used the versions currently found in Servo.
Fixes #94.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/95)

Specify versions for serde and serde_macros (fixes #94)

---

Cargo.toml
src/parser.rs
src/tokenizer.rs

Used to tell Servo to recalulate styles on window resize (servo/servo#8754).
r? @SimonSapin
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/99)

Record whether viewport percentage dimensions are seen

---

Cargo.toml
src/tokenizer.rs

`Tokenize::source_location` takes an "position" counting UTF-8 bytes since the start of the stylesheet and returns a "location" made of a line number and column number. To avoid counting lines from the start every time, it saves some results after each call.
Previously we would only save the position of the last known line break, so calling source_location() for name positions within a single long line would keep searching from that point for the next line break and therefore take O(n²) time.
Very long lines can easily happen when a CSS minifier is used.
We now save the full (line, column) result from the last call.
See https://github.com/servo/servo/issues/9897#issuecomment-194034456 and https://github.com/servo/servo/issues/9897#issuecomment-194167211
r? @jdm
---
This change is [<img …

Fix accidentally quadratic algorithm

---

src/serializer.rs
src/tests.rs

Added escape of NULL (U+0000) char and escape for characters
in the range [\1-\1f] (U+0001 to U+001F) or U+007F
according to https://drafts.csswg.org/cssom/#serialize-an-identifier
Needed for proper CSS tests https://github.com/servo/servo/issues/10685
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/104)

New characters escaped in serialize_name

---

.travis.yml
Cargo.toml
src/color.rs
src/lib.rs
src/serializer.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/106)

Allow serde 0.8 and remove use of compiler plugins

---

Cargo.toml
src/css-parsing-tests/rule_list.json
src/css-parsing-tests/stylesheet.json
src/css-parsing-tests/stylesheet_bytes.json
src/parser.rs
src/rules_and_declarations.rs

Per spec change https://drafts.csswg.org/css-syntax/#parse-stylesheet
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/107)

Remove the first rule if it’s `@charset` in "parse a stylesheet"

---

Cargo.toml
src/rules_and_declarations.rs
src/tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/109)

Make rules and declarations parsers take &mut self

---

Cargo.toml
src/parser.rs
src/tests.rs

Fixes: https://bugzilla.mozilla.org/show_bug.cgi?id=1323705
r? @SimonSapin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/111)

Avoid overflowing the stack in consume_until_end_of_block.

---

.travis.yml
Cargo.toml
build.rs
src/lib.rs
src/macros/match_byte.rs
src/macros/mod.rs
src/tokenizer.rs

This makes parsing quite faster, by stripping UTF-8 logic and using tables instead of branching everywhere.
We may be able to tweak it a bit more (sometimes the table may be overkill? I don't know).
I've written the table macro so you can skip it easily if you want.
In any case, benchmark results:
Before:
> test tests::big_stylesheet ... bench:  10,392,017 ns/iter (+/- 1,954,644)
> test tests::unquoted_url   ... bench:     261,854 ns/iter (+/- 53,335)
After:
> test tests::big_stylesheet ... bench:   8,638,215 ns/iter (+/- 381,980)
> test tests::unquoted_url   ... bench:     211,863 ns/iter (+/- 73,418)
Which is quite good if you ask me.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Some perf tweaks to the tokenizer.

---

Cargo.toml

see https://bugzilla.mozilla.org/show_bug.cgi?id=1336655
r? @SimonSapin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/116)

Exclude css-parsing-tests from crate publishes

---

src/tokenizer.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/119)

Add comments to justify `unsafe` blocks.

---

Cargo.toml
src/color.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/114)

Update serde to 0.9.0

---

Cargo.toml
src/parser.rs

r? @SimonSapin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/124)

Don't heap-allocate a tokenizer for top-level parsing.

---

src/serializer.rs

Fixes [servo/servo#15947](https://github.com/servo/servo/issues/15947)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/129)

Character between U+0001 ~ U+001F in string should be escaped when serialized

---

Cargo.toml
src/lib.rs
src/tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/130)

Stop using temp files and an external program for diffs in test failures

---

macros/lib.rs

This avoids https://github.com/rust-lang/rust/issues/40978.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/131)

Mark invalid Rust as text-only documentation.

---

src/tests.rs
src/tokenizer.rs

The following commit:
* Removes char logic from consume_numeric.
* Rearranges exponent parsing to look at one char in the common case
(presumably not a big deal).
This makes the benchmark added in the first commit go from:
test tests::numeric      ... bench:  48,221,308 ns/iter (+/- 3,356,881)
to:
test tests::numeric      ... bench:  43,656,802 ns/iter (+/- 1,323,570)
on my machine.
Which is pretty much a micro-optimization, but perhaps it's worth given how
common these values are.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/132)

Numeric faster

---

Cargo.toml
macros/Cargo.toml
macros/lib.rs
src/macros.rs

Fix #126.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/140)

Remove broken support for bindings inside match_ignore_ascii_case.

---

Cargo.toml
src/color.rs
src/css-parsing-tests/color3.json

`some_f32 as i32` would warp
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/141)

Fix overflow in rgb() parsing.

---

src/serializer.rs

b'\n' and b'\r' should be serialized to '\\a ' and '\\d ' respectively, rather than '\\A ' and '\\D '. Simply let them be treated the same way as other escaped character should be fine.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/145)

Treat \n and \r same as other escaped characters

---

Cargo.toml
src/color.rs

Useful to parse quirky colors.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/146)

Introduce Color::parse_hash

---

Cargo.toml
src/color.rs
src/lib.rs
src/nth.rs
src/parser.rs
src/rules_and_declarations.rs
src/tests.rs
src/unicode_range.rs

This shouldn't be merged until the related Servo and Gecko work is complete, but I figured I would put this up for feedback.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/143)

Return more specific errors from parsing APIs

---

Cargo.toml
src/color.rs
src/lib.rs
src/nth.rs
src/parser.rs
src/rules_and_declarations.rs
src/tests.rs
src/unicode_range.rs

The API changes should not merge until the downstream consumers are ready.
This reverts commit 0a70d228aca1f60b1d838bbe4b471bfa9c6bb557, reversing
changes made to fc0bdcd1845e3aa616c3bdd15127aed259b87cb8.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/148)

Revert parse error changes

---

Cargo.toml
src/color.rs
src/lib.rs
src/nth.rs
src/parser.rs
src/rules_and_declarations.rs
src/tests.rs
src/unicode_range.rs

This is #143 with an extra commit added to accommodate changes requested in https://github.com/servo/servo/pull/16752.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/155)

Return meaningful error values when parsing

---

src/tokenizer.rs

I suppose nothing is going to be happy if a CSS file can contain over 4G lines or columns...
All Servo rules have `SourceLocation` stored, so reducing its size is probably worth.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/157)

Use u32 for SourceLocation

---

Cargo.toml
src/color.rs
src/compact_cow_str.rs
src/lib.rs
src/nth.rs
src/parser.rs
src/rules_and_declarations.rs
src/serializer.rs
src/size_of_tests.rs
src/tests.rs
src/tokenizer.rs
src/unicode_range.rs

Hopefully improving parsing performance: https://bugzilla.mozilla.org/show_bug.cgi?id=1347408
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/159)

Reduce the size of Token

---

src/parser.rs
src/tests.rs

Also add a test for this behavior. I was wondering about this myself, and figure it might save
others time in the future. Thanks for the library!
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/161)

Clarify comment for parse_until_before; it also stops parsing at the end of the input.

---

Cargo.toml
src/color.rs
src/css-parsing-tests/README.rst
src/css-parsing-tests/color3.json
src/tests.rs

Serialize currentcolor as canonicalized form instead of currentColor. This is needed for servo/servo#15397
I'm not sure about version bump though. Is that a breaking change?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/162)

Serialize currentcolor as canonicalized form

---

Cargo.toml
src/parser.rs
src/rules_and_declarations.rs
src/serializer.rs
src/tests.rs
src/tokenizer.rs

This is a grab bag of changes that were important for getting Stylo tests passing.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/168)

Parser changes for Gecko integration

---

Cargo.toml

package.exclude takes glob syntax for determining what files to exclude
when excluding directories.
Fixes #169.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/170)

actually exclude test files from packaging

---

Cargo.toml
src/tests.rs
src/tokenizer.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/175)

Fix a panic in bad-url token parsing. Fix #174.

---

Cargo.toml
src/tests.rs
src/tokenizer.rs

https://bugzilla.mozilla.org/show_bug.cgi?id=1383975
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/176)

Fix another panic in bad-url token parsing

---

Cargo.toml
src/lib.rs
src/nth.rs
src/parser.rs
src/rules_and_declarations.rs
src/size_of_tests.rs
src/tests.rs
src/tokenizer.rs
src/unicode_range.rs

Before this PR, the `source_location` and `current_source_location` iterated (again) through input bytes separately from tokenization in order to count newline characters and determine the line number of some piece of a stylesheet.
This PR makes this counting happen during tokenization instead, where we already have a pass looking at every bytes.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/177)

Count line-numbers during tokenization

---

Cargo.toml
src/parser.rs
src/size_of_tests.rs
src/tests.rs
src/tokenizer.rs

Change the parser to extract the source map URL from directive comments.
The relevant spec is here:
https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit#heading=h.lmz475t4mvbx
This is part of similar work being done in M-C in
https://bugzilla.mozilla.org/show_bug.cgi?id=1388855
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/178)

Extract source map URL from directive comments

---

Cargo.toml
src/css-parsing-tests/component_value_list.json
src/lib.rs
src/serializer.rs
src/tests.rs

I'm not sure whether it can be simplified... and I probably need some more idea for how should I test it... But things look fine so far.
This should probably goes to an independent crate at some point.
It should fix servo/servo#17205.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/173)

Serialize number to no more than necessary precision

---

Cargo.toml
src/parser.rs
src/rules_and_declarations.rs
src/tokenizer.rs

(and use it it rule parsing to make it hopefully more efficient.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/181)

Add Parser::skip_whitespace

---

src/tests.rs
src/tokenizer.rs

skip_cdc_and_cdo had an off-by-one error when trying to skip the CDC.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/182)

Fix an off-by-one error in CDC skipping

---

Cargo.toml
src/parser.rs
src/tests.rs

This patch adds ParserInput::new_with_line_number_offset, a new
constructor that calls Tokenizer::with_first_line_number.  Servo has its
own code for tracking the initial line number, but that code can be
replaced by this.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/184)

Provide ParserInput::new_with_line_number_offset

---

Cargo.toml
src/parser.rs

This fixes (at least some of) the test failures at https://github.com/servo/servo/pull/18171
In code like this:
```css
unsupported selector ! { stuff }
valid selector { color: green }
```
`rules_and_declarations::parse_qualified_rule` would leave the parser just after the first `{` with `Parser::at_start_of == Some(BlockType::CurlyBracket)`. The latter means that, unless `Parser::parse_nested_block` is called, the parser needs to skip over this block until the matching `}` before doing anything else. This PR makes `Parser::skip_whitespace` and `Parser::skip_cdc_and_cdo` (both added recently in https://github.com/servo/rust-cssparser/pull/181) take care of `Parser::at_start_of` correctly the same way `Parser::next` does.
---
This change is [<img …

Fix interaction of skip_whitespace and nested blocks

---

Cargo.toml
src/lib.rs
src/parser.rs

… to avoid allocating in common cases.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/186)

Use a SmallVec instead of Vec in consume_until_end_of_block

---

Cargo.toml
src/parser.rs

These showed up in some perf profiles as non-inlined parts of inlined parser methods.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/183)

Inline more parser methods.

---

Cargo.toml
src/parser.rs
src/tokenizer.rs

The only user of it is going away in servo/servo#18267.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/187)

parser: Remove ability to look for viewport percentages.

---

src/tokenizer.rs

next_token has this code:
if is_ident_start(tokenizer) { IDHash(consume_name(tokenizer)) }
else if !tokenizer.is_eof() && match tokenizer.next_byte_unchecked() {
b'a'...b'z' | b'A'...b'Z' | b'0'...b'9' | b'-' | b'_' => true,
b'\\' => !tokenizer.has_newline_at(1),
_ => !b.is_ascii(),
} { Hash(consume_name(tokenizer)) }
I noticed that the `_` case incorrectly checks whether `b` is ASCII,
rather than the current byte.
However, on further inspection, it turns out that this can't be run,
because all such cases would have been filtered out by is_ident_start.
This patch clarifies this code by removing the dead cases and adding a
comment.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

Clarify some dead code

---

Cargo.toml
src/color.rs
src/lib.rs
src/serializer.rs
src/tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/190)

Avoid std::fmt in serialization code

---

src/tokenizer.rs

UnquotedUrl is only used for url() without quotes, so update the
documentation to say so.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/191)

Change documentation of UnquotedUrl

---

src/parser.rs
src/tests.rs
src/tokenizer.rs

This series changes columns numbers to be reported in units of UTF-16 characters.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/192)

Utf 16 columns

---

src/css-parsing-tests/one_rule.json
src/css-parsing-tests/rule_list.json
src/css-parsing-tests/stylesheet.json
src/rules_and_declarations.rs
src/tests.rs

This change makes `AtRuleParser::parse_prelude` always return a prelude if parsed successfully, so that at-rules which do not accept block can be handled in two phases just like those with block.
This is important because at-rules without block usually have side effects. If `parse_prelude` executes the side effect, but `parse_at_rule` later determined that the rule is actually invalid (e.g. because it is followed by a block), there is no way for impl of `AtRuleParser` to undo the side effect.
It provides the necessary parser side change for fixing [Gecko bug 1388911](https://bugzilla.mozilla.org/show_bug.cgi?id=1388911).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser …

Have at-rule without block handled in two stages as well

---

src/parser.rs
src/serializer.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/193)

Use an array instead of `match` for hexadecimal digits.

---

Cargo.toml
src/serializer.rs
src/tests.rs
src/tokenizer.rs

This will help fix https://bugzilla.mozilla.org/show_bug.cgi?id=1396664.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/194)

Fix serialization of bad-string and bad-url tokens

---

Cargo.toml
src/parser.rs

Part 3 of the fix for Gecko bug 1397614 <https://bugzilla.mozilla.org/show_bug.cgi?id=1397614>.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/195)

Avoid array overallocation when parsing background-image property

---

Cargo.toml
src/parser.rs
src/tests.rs
src/tokenizer.rs

Change cssparser to report columns as being 1-based, for Gecko
compatibility.  Formerly this offsetting was handled in Servo, but it
wasn't done on all code paths, so we agreed to put it into
rust-cssparser.  For some background, see:
https://bugzilla.mozilla.org/show_bug.cgi?id=1398869
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/196)

Report columns as 1-based

---

Cargo.toml
src/parser.rs
src/size_of_tests.rs
src/tests.rs
src/tokenizer.rs

In addition to the sourceMappingURL comment, there is a second special
comment, "sourceURL", that can be used to set the "display name" of a
style sheet for developer tools.  This name is also used as the base
URL for the source-map URL resolution algorithm.  sourceURL is
described here:
https://blog.getfirebug.com/2009/08/11/give-your-eval-a-name-with-sourceurl/
The relevant Firefox bug is here:
https://bugzilla.mozilla.org/show_bug.cgi?id=880831
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/197)

Preserve sourceURL comment in parser

---

Cargo.toml
src/nth.rs

Reusing our tokenizer because it already saturates.
There is no way to reliably get the error details from `"-12034".parse()`, since the error type is opaque and the description strings may change.
This fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1401016
A less risky but also less correct fix is to simply return an error when `.parse()` fails.
r? @SimonSapin
Don't land until I can get a try run; nth-child has weird tokenization rules that we need to respect here (which is why I'm creating a new tokenizer in the first place)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/198)

Saturate if nth-child value is out of range

---

Cargo.toml
src/color.rs
src/lib.rs
src/nth.rs
src/parser.rs
src/rules_and_declarations.rs
src/size_of_tests.rs
src/tests.rs
src/unicode_range.rs

This is part of https://bugzilla.mozilla.org/show_bug.cgi?id=1378861
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/200)

Include a SourceLocation in all error types

---

Cargo.toml
build.rs

This is more robust, I’m unsure which release this rustc change will go into.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/206)

Use feature testing over version number parsing.

---

Cargo.toml
build.rs
build/match_byte.rs
macros/Cargo.toml
macros/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/211)

Update syn to 0.12 and quote to 0.4

---

.travis.yml
macros/Cargo.toml

This feature is needed for that crate to compile but since CI was never
compiling it on its own and that cargo features are additive, this never
got caught.
Fixes #214
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/215)

Add the extra-traits feature to syn in the cssparser-macros crate

---

Cargo.toml
src/unicode_range.rs

No browser does that. This causes test failures in Gecko.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/218)

Have UnicodeRange not serialize question marks.

---

Cargo.toml
src/serializer.rs

I want to use it to remove some stupid allocations in Servo, which effectively
do:
serialize_identifier(format!("--{}", custom_prop_name));
And could do instead:
write_str("--");
serialize_name(custom_prop_name);
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/221)

Expose serializer::serialize_name.

---

Cargo.toml
src/lib.rs

Whoops, serializer is a private module :)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/222)

Actually expose serialize_name.

---

Cargo.toml
procedural-masquerade/lib.rs

This is a prospective fix for https://github.com/servo/servo/issues/21038.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/224)

procedural-masquerade: Give more stack to procedural-masquerade macros.

---

Cargo.toml
src/rules_and_declarations.rs
src/tests.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/226)

Include source location in param of rule parsers

---

Cargo.toml
src/parser.rs
src/tests.rs
src/tokenizer.rs

Differential Revision: https://phabricator.services.mozilla.com/D9609
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/230)

tokenizer: Look for both env() and var() functions.

---

Cargo.toml
build/match_byte.rs
macros/Cargo.toml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/229)

Update syn and bump version

---

Cargo.toml
src/parser.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/235)

Add Parser::new_error_for_next_token

---

README.md

The `ast.rs` file does not exist anymore... so I'm assuming that's what's supposed to be linked to now?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/240)

README.md fix ast link

---

Cargo.toml
src/color.rs

This will be useful for my efforts of avoiding intermediate representations in
the style system.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/241)

color: Make cssparser::RGBA #[repr(C)].

---

.travis.yml
Cargo.toml
build.rs
build/match_byte.rs
macros/lib.rs
procedural-masquerade/lib.rs
src/color.rs
src/cow_rc_str.rs
src/from_bytes.rs
src/lib.rs
src/macros.rs
src/nth.rs
src/parser.rs
src/rules_and_declarations.rs
src/serializer.rs
src/size_of_tests.rs
src/tests.rs
src/tokenizer.rs
src/unicode_range.rs

See individual commits
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/245)

Fix a "will be a hard error" warning + drive-by

---

src/rules_and_declarations.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/246)

Fix typo in documentation

---

Cargo.toml
build.rs
src/color.rs
src/macros.rs
src/nth.rs
src/serializer.rs
src/tokenizer.rs

Fix deprecation warnings for `mem::uninitialized`. (They also affected other crates, since it’s used in a public macro.)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/252)

Use MaybeUninit when available 

---

.travis.yml
Cargo.toml
build/match_byte.rs
macros/Cargo.toml
macros/lib.rs

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/257)

Update syn related dependencies to 1.0 and bump version

---

.travis.yml
Cargo.toml
build.rs
src/macros.rs

This raises the minimum Rust version to 1.36.0, so this is a breaking change.

Unconditionally use MaybeUninit

---

src/rules_and_declarations.rs

The generic parsing functions require lifetime annotations to build because of https://github.com/rust-lang/rust/issues/42508. 
However, this creates a warning from the `late_bound_lifetime_arguments` compatibility lint, described in https://github.com/rust-lang/rust/issues/42868, because they have both early-bound and late-bound lifetime parameters.
This PR works around this warning, in a functional but sub-optimal way. The result is quite verbose, and I didn't manage to "convince" rustc to think all lifetimes were early-bound at the `fn` definitions, but manages to avoid triggering both https://github.com/rust-lang/rust/issues/42508 and the lint, by passing these closures via variables at each call-site.
Fixes https://github.com/servo/rust-cssparser/issues/254

Work around warning from `late_bound_lifetime_arguments` lint

---

src/color.rs
src/nth.rs
src/parser.rs
src/rules_and_declarations.rs
src/unicode_range.rs

I was doing some performance work and some of these clone() calls appear in
profiles. There's more to do but I'd rather take out the low hanging fruit first
:)

Clean up a bit now that lifetimes are non-lexical.

---

procedural-masquerade/Cargo.toml
procedural-masquerade/lib.rs

CC https://github.com/rust-lang/rust/pull/73345#issuecomment-646895843

Make procedural-masquerade resilient to macro input pretty-printing changes

---

procedural-masquerade/lib.rs

This PR fixes this https://travis-ci.com/github/servo/rust-cssparser/jobs/351868518 build failure in https://github.com/servo/rust-cssparser/pull/275 PR

Add rustfmt::skip to skip rustfmt for ProceduralMasqueradeDummyType enum

---

Cargo.toml
src/rules_and_declarations.rs
src/tests.rs

This is:
* More generic, as the state has more information like the source
index.
* Slightly cheaper to compute, as the source location requires math to
compute, which the parser state doesn't
I need this to improve CSS sanitization in Gecko.
https://bugzilla.mozilla.org/show_bug.cgi?id=1680084

Pass rule start to parser rather than just a location.

---

Cargo.toml
src/macros.rs

By inlining the happy-path. this improves CSS parsing performance of
benchmarks, even on PGO builds.

macros: Optimize cssparser_internal_to_lowercase for already-lowercase inputs.

---

Cargo.toml
src/lib.rs
src/rules_and_declarations.rs
src/tests.rs

This is needed for @layer, which can be block or blockless.

Tweak at-rule parsing API to allow a single at-rule to be block or blockless.

---

procedural-masquerade/lib.rs
src/css-parsing-tests/stylesheet_bytes.json
src/macros.rs
src/parser.rs
src/rules_and_declarations.rs

This PR aims to fix assorted typos in comments and test descriptions.

Misc. typo fixes.

---

.github/workflows/main.yml
Cargo.toml

phf 0.8 still uses rand_core version <0.6.2 which suffer from [CVE-2021-27378](https://nvd.nist.gov/vuln/detail/CVE-2021-27378).
Every crate depends on it will be warned by cargo audit.

Update phf to 0.10

---

Cargo.toml

Sorry I forgot to add the version bump in previous PR.
~~I bump the patch version since this doesn't add or change anything in cssparser itself?~~
Just realized this changed the minimum rust version.

Bump version to 0.30.0

---

Cargo.toml
src/serializer.rs

Update itoa to 1.0

---

Cargo.toml
src/macros.rs
src/nth.rs
src/serializer.rs
src/tests.rs
src/tokenizer.rs

The `matches` crate can be removed since MSRV is 1.56.

Use the `std::matches!` macro

---

src/color.rs
src/lib.rs
src/tests.rs

This change cleans up the Color enum to better represent the <color> type in the spec and reduce the overall size of the color type.

Remove AbsoluteColor abstraction

---

src/color.rs

The github mirror should not become the new official place for the csswg specifications, so changing the urls back to drafts.csswg.org/css*

Fix csswg urls

---

src/color.rs

Combine the rules of legacy and new parsing into single functions.  This allows for a much clearer separation of which keywords support which syntax.  RGB is still special, because it the components **must** be of the same type (numbers or percentages).  Most of the color functions are using the new syntax, but some special notes:
- `RGB` uses it's own parser as mentioned.
- `HSL` supports both legacy and new syntax.
- `HWB` only supports new suntax.
- _ the rest supports the new syntax only.
These changes are also in preparation of introducing the `none` keyword where it is much more important to know which syntax is being used, as legacy syntax does **not** support the `none` keyword.

Combine parsing into legacy and new parsing.

---

src/color.rs
src/tests.rs

Parsing is not done in 2 forms as per the spec.  Legacy and new syntax.  For rgb and hsl where both are valid, first one is tried and if it fails, we try the other.
We also store hsl and hwb values directly without converting them to rgba at parse time.  The conversion only happens how before serializing.

Do not convert hsl/hwb to RGB at parse time to not loose precision

---

src/color.rs
src/lib.rs
src/tests.rs

For each color component, we allow the "none" keyword.  The keyword will be kept in place for serialization.  The "none" keyword is not allowed in the legacy syntax.
`rgb` and `hsl` are handled special, because they support the legacy color syntax.  They also cannot be combined, because rgb cares about the type of the components, and hsl does not.

Add none keyword

---

src/color.rs
src/lib.rs

- Add documentation where needed.
- Remove #[repr(C)] from structs.  These are not needed any more and doesn't really do anything now that the types are Option<_>.
- Fix links so that they work in docs.
- Small clippy fixes.
@emilio For publishing all the new color changes as 0.30 to crates.io, any other suggestions on what to clean up?

Cleanup for crates.io release

---

src/macros.rs

In this function you use the unsafe keyword for almost the entrie function body. 
We need to mark unsafe operations more precisely using unsafe keyword. Keeping unsafe blocks small can bring many benefits. For example, when mistakes happen, we can locate any errors related to memory safety within an unsafe block. This is the balance between Safe and Unsafe Rust. The separation is designed to make using Safe Rust as ergonomic as possible, but requires extra effort and care when writing Unsafe Rust.
Hope this PR can help you.
Best regards.
**References**
https://doc.rust-lang.org/nomicon/safe-unsafe-meaning.html
https://doc.rust-lang.org/book/ch19-01-unsafe-rust.html

Shrink unsafe block

---

src/parser.rs

Previously the `ParseError` struct did not implement `std::error::Error` or `std::fmt::Display`. This meant that `ParseError` was not boxable into an "any error" box like `anyhow::Error`. This commit adds Error and Display implementations for ParseError and friends.
Rebase + MSRV fix of #298

Make `ParseError` a `std::error::Error`

---

src/cow_rc_str.rs
src/tests.rs
src/tokenizer.rs

This PR aims to fix a few minor deprecation warnings.
See https://blog.rust-lang.org/2020/04/23/Rust-1.43.0.html#library-changes and https://doc.rust-lang.org/stable/std/usize/index.html for details.

Replace deprecated std constants by associated constants.

---

Cargo.toml
src/rules_and_declarations.rs

The API change is needed regardless (we need a declaration parser that also parses qualified rules).
The implementation details are a bit subject to change so make it opt-in.

[css-nesting] Trivial-ish nesting API changes.

---

src/lib.rs
src/macros.rs

- Allow the `_cssparser_internal_to_lowercase` macro to be used in crates that set `#[forbid(unsafe)]`.
- Document the safety invariant for this unsafe block
- Wrap the `unsafe` block in the `_cssparser_internal_to_lowercase` macro in an `#[inline(always)]` function.
-  Add comments
- https://github.com/DioxusLabs/taffy/pull/460#discussion_r1174152707

Encapsulate unsafe in `_cssparser_internal_to_lowercase` macro

---

src/rules_and_declarations.rs

Without the new nesting proposal, a stray semicolon in a media rule eats the next rule.

[css-nesting] Fix body parsing recovery when nesting is not enabled.

---

src/color.rs
src/lib.rs

This function is very handy in other places and is worth making public.  Right now it will be used to generate specified value colors in Gecko.

Make the serialize_alpha function public.

---

macros/Cargo.toml
macros/lib.rs

This makes no effort to gracefully handle errors that the old code didn't handle.

Update cssparser-macros to syn 2

---

Cargo.toml

They were used before the separate proc-macro crate was created, but aren't anymore.

Remove build dependencies

---

src/rules_and_declarations.rs

This fixes issues that were found when enabling nesting by default on Nightly.
It matches the spec (see new link) more closely. The places where we diverge (continuing rather than stopping when hitting right-curly, etc) are not really observable because of how our other APIs work (parse_nested_block in particular, for that case).

[css-nesting] Make our nesting implementation match the new spec better.

---

src/cow_rc_str.rs

cow-rc-str: Use ptr::NonNull.

---

.github/workflows/main.yml
Cargo.toml
src/tests.rs

Resolves #346. Some tests that take over a minute to run under miri are skipped (on CI only):
* color3_hsl
* color4_hwb
* color4_lab_lch_oklab_oklch
* no_stack_overflow_multiple_nested_blocks
* numeric
* roundtrip_percentage_token

Run miri on CI

---

src/parser.rs
src/tests.rs
src/tokenizer.rs

It can be implemented on top of the parser anyways, and after bug 1847440 we won't use it anymore.

parser: Remove the line-number-offset mechanism.

---

src/color.rs

Because the structs are public it only make sense to make the getters public as well.

Make NumberOrPercentage and AngleOrNumber getters public.

---

src/serializer.rs
src/tests.rs

Fixes #266
Making TokenSerializationType public is useful to describe a CSS string that is already known to be valid in cases when the TokenSerializationTypes of the start and end of the CSS string is needed, but Tokens are not.
This helps with creating a custom_properties::VariableValue from the CSS string of a computed value for CSS Properties and Values, see Mozilla bug 1858305 [1].
[1]: https://bugzilla.mozilla.org/show_bug.cgi?id=1858305

Replace TokenSerializationType with TokenSerializationTypeVariants

---

src/parser.rs

Fix the documentation of what certain parse functions return

---

Cargo.toml

Useful for profiling via [samply](https://github.com/mstange/samply) or perf.

Add a profiling cargo profile.

---

src/nth.rs
src/parser.rs
src/rules_and_declarations.rs

Further clarifications in docs for what errors are returned.

---

.github/workflows/main.yml
color/lib.rs
src/color.rs
src/parser.rs
src/rules_and_declarations.rs
src/serializer.rs
src/tests.rs
src/tokenizer.rs

I added ignores/allows for the remaining lints.
The `1.63.0` jobs revealed clippy warnings that were not present in stable/beta/nighty, which was strange, but they are fixed also.

Add cargo fmt and cargo clippy checks to CI

---

Cargo.toml
color/lib.rs
color/tests.rs
src/color.rs

Also bump version to 0.34, because this is a breaking change.

Make PredefinedColorSpace follow the convention of parse() and ToCss

---

src/parser.rs
src/rules_and_declarations.rs

This implements the:
> If the first two non-<whitespace-token> values of rule’s prelude are
> an <ident-token> whose value starts with "--" followed by a
> <colon-token>, then...
From https://drafts.csswg.org/css-syntax/#consume-qualified-rule
Mozilla Bug: 1884879
Differential Revision: https://phabricator.services.mozilla.com/D207796

parser: Implement recent syntax spec change to avoid parsing custom properties that look like selectors as rules.

---

.github/workflows/main.yml
Cargo.toml
src/from_bytes.rs
src/serializer.rs
src/tokenizer.rs

Now that [malloc_size_of](https://github.com/servo/malloc_size_of) is published to crates.io we are moving the trait implementations of [MallocSizeOf](https://docs.rs/malloc_size_of/latest/malloc_size_of/trait.MallocSizeOf.html) and related traits into the crates that define the types. This will avoid the situation where depending on `malloc_size_of` pulls in a large number of dependencies.
This PR adds the implementation of `MallocSizeOf` to the `cssparser` crate.

Implement `MallocSizeOf` for cssparser types

---

Cargo.toml
color/Cargo.toml

Can we get a new release of `cssparser`?
Servo depends on `cssparser` from crates.io, and the latest version of Stylo depends on unreleased breaking changes to `cssparser`.

Bump version to v0.35.0
