- .travis.yml
Bors is now enabled for this repo, so this can be auto-landed.
> Add notifications from Travis to Homu.

- Cargo.toml
- src/parser.rs
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/88)
> Add Delimiter::Bang for CSS Custom Properties.

- Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/92)
> Allow heapsize 0.2.z

- Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/93)
> Bump to 0.5.1

- Cargo.toml
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/98)
> Bump serde to 0.7

- src/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/125)
> Fix doc typo

- procedural-masquerade/lib.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/139)
> Let define_proc_macros! handle early returns.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/151)
> Bump version to 0.13.6

- Cargo.toml
- src/css-parsing-tests/component_value_list.json
- src/tokenizer.rs
See https://bugzilla.mozilla.org/show_bug.cgi?id=1366977
r? @SimonSapin
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/152)
> Match float parse rounding with Gecko

- Cargo.toml
- src/color.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/149)
> Update to serde 1.0 and bump version

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/163)
> Unbump version

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/204)
> Breaking version bump to account for #203.

- Cargo.toml
- build.rs
- macros/lib.rs
- src/nth.rs
- src/parser.rs
- src/rules_and_declarations.rs
- src/serializer.rs
- src/size_of_tests.rs
- src/tokenizer.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/205)
> Upgrade to rustc 1.23.0-nightly (33374fa9d 2017-11-20)

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/208)
> Update smallvec to 0.6 and bump version

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/212)
> Update difference to 2.0

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/216)
> Update itoa to 0.4 and bump version

- build.rs
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/231)
> Remove some warnings.

- macros/Cargo.toml
forgot to do when I bumped syn
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/232)
> Bump cssparser-macros version

- procedural-masquerade/lib.rs
- src/size_of_tests.rs
This will allow #227 to merge.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/238)
> Fix nightly warnings and errors.

- Cargo.toml
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/227)
> deps: bump encoding_rs to 0.8

- Cargo.toml
- src/lib.rs
- src/tests.rs
Fixes #253
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/servo/rust-cssparser/255)
> Switch from rustc-serialize to serde_json

- Cargo.toml
> Bump smallvec to 1.0, release new minor version (0.27.2)

- Cargo.toml
- color/Cargo.toml
- macros/Cargo.toml
Tested with:
cargo +nightly update -Zminimal-versions
cargo check --all-targets
cargo +nightly check --all-targets --all-features
> Fix dependencies minimal versions

- Cargo.toml
- color/Cargo.toml
- color/lib.rs
- color/tests.rs
- macros/lib.rs
- src/color.rs
- src/cow_rc_str.rs
- src/macros.rs
- src/nth.rs
- src/parser.rs
- src/rules_and_declarations.rs
- src/serializer.rs
- src/tests.rs
- src/tokenizer.rs
- src/unicode_range.rs
This is #377 but rebased, without the merge commits, and commits squashed by topic.
> Serde + clippy fixes
